version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"
#      - "3000:3000"
    command: npm run dev -- --host
