---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: super-cool-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
#    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bauerlein.dev
    secretName: quickstart-example-tls
  rules:
  - host: bauerlein.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: super-cool-service
            port:
              number: 80
