name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-frontend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image
        run: docker build -t ghcr.io/markus-brln/website/frontend:$(date +'%Y%m%d%H%M') -f ./frontend/app/Dockerfile ./frontend/app
      - name: Push the Docker image with timestamp format YYYYMMDDHHMM
        run: docker push ghcr.io/markus-brln/website/frontend:$(date +'%Y%m%d%H%M')
      - name: List images
        run: docker images
