name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ghcr.io/markus-brln/website/frontend:0.1.0 -f ./frontend/app/Dockerfile ./frontend/app
